[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/entries"
  to = "/.netlify/functions/entries"
  status = 200

[[redirects]]
  from = "/api/gabarito"
  to = "/.netlify/functions/gabarito"
  status = 200
